race_mapping:
    "Race/American_Indian": "RACE:American Indian or Alaska Native"
    "Race/White": "RACE:White"
    "Race/Black": "RACE:Black or African Americann"
    "Race/Asian": "RACE:Asian"
    "Race/Pacific_Islander": "RACE:Native Hawaiian or Other Pacific Islander"
gender_mapping:
    "Gender/M": "GENDER:M"
    "Gender/F": "GENDER:F"
ethnicity_mapping:
    "Ethnicity/Hispanic": "ETHNICITY:Hispanic or Latino"
    "Ethnicity/Not Hispanic": "ETHNICITY:Not Hispanic or Latino"
data_to_umls_source_map:
    "CPT4": "CPT"
    "HCPCS": "HCPCS"
    "ICD10PCS": "ICD10PCS"
    "RxNorm": "RXNORM"
    "SNOMED": "SNOMEDCT_US"
    "LOINC": "LOINC"
    "RxNorm Extension": "RXNORM"
    "CVX": "CVX"
    "ICD9Proc": "ICD9CM"
vocab_to_umls_source_map:
    "ICD9": "ICD9CM"
    "ICD10": "ICD10CM"
    "ICD9CM": "ICD9CM"
    "ICD10CM": "ICD10CM"
    "LOINC": "LOINC"
    "NDC": "NDC"
    "RXNORM": "RXNORM"
    "HCPCS": "HCPCS"
    "CPT4": "CPT"
    "CPT": "CPT"
    "ICD10PCS": "ICD10PCS"
    "SNOMED": "SNOMEDCT_US"